#!/bin/bash
# Build for AMD64
# Builder
version: '3'
services:

  debunker:
    #container_name: debunker
    build: '.'
    restart: always
    # ports:
    #  - '8080:2000'
    networks:
      static-network:
        ipv4_address: 10.12.0.3
    tty: true
    stdin_open: true
  chrome:
   image: selenium/standalone-chrome:85.0
   hostname: chrome
   ports:
        - "4444:4444"
   networks:
      static-network:
        ipv4_address: 10.12.0.4
networks:
  static-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.12.0.0/16
          gateway: 10.12.0.1
