#!/bin/bash
# Build for AMD64
# Builder
version: '3'
services:
  db:
    #container_name: db
    image: mariadb:11
    restart: always
    environment:
      MARIADB_DATABASE: 'debunker'
      MARIADB_ROOT_PASSWORD: '309urje4'
    #ports:
    #  - '3306:3306'
    volumes:
      - '/workstorage1/data/debunker-assistant:/var/lib/mysql'
    networks:
      static-network:
        ipv4_address: 10.7.0.4
  debunker:
    #container_name: debunker
    build: '.'
    restart: always
    # ports:
    #  - '8080:2000'
    depends_on:
      - db
    networks:
      static-network:
        ipv4_address: 10.7.0.3
    tty: true
    stdin_open: true
networks:
  static-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.0.0/16
          gateway: 10.7.0.1
